services:
  - type: web
    name: farmer-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: firebase_config.json
